# Generated by Django 5.0.4 on 2024-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_github_link_blog_linkedin_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=50)),
                ('about_description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='linkedin_link',
        ),
    ]
