# Generated by Django 5.0.4 on 2024-05-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about_followus_remove_blog_github_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='FollowUs',
        ),
    ]
