# Generated by Django 5.0.4 on 2024-05-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_about_followus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='followus',
            options={'verbose_name_plural': 'FollowUs'},
        ),
        migrations.AddField(
            model_name='followus',
            name='followus_headding',
            field=models.CharField(default='Follow Us', max_length=50),
        ),
    ]
