# Generated by Django 5.0.4 on 2024-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_about_options_alter_followus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followus',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='followus',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='followus',
            name='link',
            field=models.URLField(default=True),
        ),
    ]
